#pragma once

#undef MOUSEKEY_INTERVAL
#undef MOUSEKEY_DELAY
#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_MAX_SPEED
#undef MOUSEKEY_WHEEL_DELAY
#undef MOUSEKEY_WHEEL_MAX_SPEED
#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#undef DEBOUNCE
#undef FORCE_NKRO
#undef QMK_KEYS_PER_SCAN


#define MOUSEKEY_INTERVAL          16
#define MOUSEKEY_DELAY            116
#define MOUSEKEY_TIME_TO_MAX       60
#define MOUSEKEY_MAX_SPEED          5
#define MOUSEKEY_WHEEL_DELAY      128
#define MOUSEKEY_WHEEL_MAX_SPEED    1
#define MOUSEKEY_WHEEL_TIME_TO_MAX  1

#define DEBOUNCE 5

#define FORCE_NKRO
#define QMK_KEYS_PER_SCAN 8
